name: bandit

on:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  bandit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Run Bandit Scan
        uses: lukehinds/bandit-action@new-action
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "."
          exit_zero: "true"
          recursive: "true"
