name: black

on: [push, pull_request]

permissions:
  contents: read

jobs:
  black:
    name: black Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.11]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: update pip
        run: python3 -m pip install --upgrade pip

      - name: pip install python packages for testing
        # run: pip install black pylint mypy
        run: pip install black

      - name: black testing
        run: |
          # shellcheck disable=SC2046
          black --diff --check $(git ls-files '*.py' ':!:docs/source/*')
