name: dependency scan

on:
  pull_request:
    branches: [main]
    #paths-ignore:
    #  - '.github/**'

env:
  DEP_PATH: requirements.txt

permissions:
  contents: read

jobs:
  safety:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip install
        run: |
          pip --version
          python -m pip install .

      - name: Security vulnerabilities scan
        run: |
          pip --version
          python -m pip install .
          safety scan

  pip-audit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip install
        run: |
          pip --version
          python -m pip install .

      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          inputs: requirements.txt
