name: isort

on: [push, pull_request]

permissions:
  contents: read

jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: isort/isort-action@v1
        with:
          requirements-files: requirements.txt
          sort-paths: "src/senzing examples tests"
