name: pytest darwin

on: [push]

env:
  PYTHONPATH: /Users/runner/work/g2-sdk-python-next/g2-sdk-python-next/src
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"

jobs:
  pytest-darwin:
    name: "pytest Senzing: ${{ matrix.senzingapi-version }}; OS: ${{ matrix.os }}; Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8", "3.11"]
        senzingapi-version: [staging]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil pytest pytest-cov pytest-schema

      - if: matrix.python-version == '3.8' || matrix.python-version == '3.9'
        name: install python libraries for python 3.8 and 3.9
        run: pip install typing_extensions

      - name: install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@v1
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}

      - name: copy /etc files
        run: sudo cp testdata/senzing-license/g2.lic /opt/senzing/g2/etc/g2.lic

      - name: copy test database files
        run: mkdir /tmp/sqlite && cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db

      - name: run pytest on tests
        run: |
          export DYLD_LIBRARY_PATH=/opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
          pytest tests/ --verbose --capture=no --cov=src/senzing

      # - name: Run pytest on examples
      #  run: |
      #    export DYLD_LIBRARY_PATH=/opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
      #    pytest examples/ --verbose --capture=no
