name: safety

on:
  push:

env:
  DEP_PATH: requirements.txt

permissions:
  contents: read

jobs:
  safety:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: update pup
        run: |
          pip3 install --upgrade pip
          pip3 --version

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@v1.0.5
