name: safety

on:
  pull_request:
    branches: [main]

env:
  DEP_PATH: requirements.txt

permissions:
  contents: read

jobs:
  safety:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@v1.0.5
        with:
          safety_args: '-i 62044'
